### ISSUE TITLE
Occasional game crash upon arriving at cross-DC travel destination

### ISSUE THREAD

**Issue by coredumperror** [NightmareXIV/Lifestream#48] opened 2024-08-10 20:33 UTC
I dunno if is necessarily Lifestream's fault, but I've now had my game crash out three times during a cross-DC travel event. 

The latest one happened as I finished the login queue to come back home to Cactuar, so maybe something that Lifestream was doing during the prep for world arrival caused the crash? 

Has anyone else seen this? I don't recall having any meaningful frequency of crashes before the last day or so.

**Comment by Limiana** [comment] 2024-08-10 22:31
Hello! Please send logs
:warning: How to send logs:
> Please do not copy logs from Dalamud's xllog window or plugin's log window. If you have encountered any problem, please do this:
> 1) Please make sure that the log level is set to "Debug" in `/xllog` top left corner. 
> 2) Recreate the problem. As soon as you have encountered the problem, without doing anything further and without restarting your game, send these files into my DM:
> `%appdata%\XIVLauncher\dalamud.log` 
> `%appdata%\XIVLauncher\dalamud.boot.log` 
> If you are encountering crashes, please additionally go to `%appdata%\XIVLauncher\` folder and search for recently created text files starting with "`dalamud_appcrash_`" and send them as well.
> Please make sure that you do not have more than one instance of the game running before sending logs.

**Comment by coredumperror** [comment] 2024-08-12 09:51
I managed to remember to do this before telling the app to restart after a crash! Here's a zip file with the two log files you requested, including several dalamud_appcrash_ files:
https://www.dropbox.com/scl/fi/jnevf1ygbi5mosc4xw53c/Dalamud-Crash-Logs.zip?rlkey=24j3299h9ay7sub1u0xfiw2un&st=pz737wv0&dl=0

**Comment by Limiana** [comment] 2024-08-23 05:35
> I managed to remember to do this before telling the app to restart after a crash! Here's a zip file with the two log files you requested, including several dalamud_appcrash_ files: 

Sorry for late reply. The issue is with the DailyDuty plugin. It probably is fixed by now, please check for updates of that plugin.

**Closed by Limiana** 2024-08-23 05:35 UTC
